if(!require('choroplethr')){

install.packages("choroplethr")

library(choroplethr)##forstate_choropleth()

}

if(!require('choroplethrMaps')){

install.packages("choroplethrMaps")##上次沒有安裝到這個package

library(choroplethrMaps)##forstate_choropleth()

}
data(df_pop_state)#記載各州人口數的資料

state_choropleth(df_pop_state)#把各州人口畫在地圖上

if(!require('rgdal')){#forfortify()

install.packages("rgdal");library(rgdal)

}

if(!require('rgeos')){#forfortify()

install.packages("rgeos");library(rgeos)

}

if(!require('maptools')){#forreadShapeSpatial()

install.packages("maptools");library(maptools)

}

tw_new<-readShapeSpatial("Taiwan/Town_MOI_1041215.shp")#檔名

names(tw_new)

## [1]"OBJECTID" "T_UID" "Town_ID" "T_Name" "T_Desc"

## [6]"Add_Date" "Add_Accept""Remark" "County_ID" "C_Name"
library(ggplot2)#forfortify(),ggplot(),ggmap()

head(tw_new$Town_ID)

##[1]100140210013211000913100141110014161000712

##368Levels:090070109007020900703090070409020010902002...6801300

tw_new.df<-fortify(tw_new,region="T_UID")#fromggplot2package
mydata<-data.frame(NAME_2=tw_new$T_Name,id=tw_new$T_UID,

prevalence=rnorm(length(tw_new$T_UID)))

head(mydata)
mydata$NAME_2<-iconv(as.character(mydata$NAME_2),#NAME_2原本是factor

from="big5",to="UTF-8")

head(mydata,10)
mydata$NAME_2<-iconv(as.character(mydata$NAME_2),#NAME_2原本是factor

from="big5",to="UTF-8")

head(mydata,10)

nba<-read.csv("http://datasets.flowingdata.com/ppg2008.csv")

head(nba)


library(reshape2)#formelt()

nba.m<-melt(nba,id.vars="Name")#寬表轉長表,以名字作依據

head(nba.m,10)


library(ggplot2)#forggplot()

ggplot(nba.m,aes(variable,Name))+#aes(x,y)

geom_tile(aes(fill=value),colour="white")+#geom_tile:區塊著色

scale_fill_gradient(low="white",high="steelblue")#數值低:白色

