---
title: "NBA 2014-2015球季 各隊分析"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
install.packages("SportsAnalytics")
library(SportsAnalytics)
NBA1415<-fetch_NBAPlayerStatistics("14-15")

## 各隊最辛苦的球員
計算依據為全季上場時間最多的球員


```{r cars}
MaxMinutes<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
#tapply(NBA1415$TotalMinutesPlayed,NBA1415$Team,max)
NBA1415MaxMinutes<-merge(NBA1415,MaxMinutes)
output<-NBA1415MaxMinutes[order(NBA1415MaxMinutes$TotalMinutes,decreasing = T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digits=2)
```

##各隊得分王
計算依據為全季總得分最多的球員

```{r pressure, echo=FALSE}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
#tapply(NBA1415$TotalPoints,NBA1415$Team,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digits=2)
```


## 各隊最有效率的球員
```{r pressure, echo=FALSE}
Maxefficiency<-aggregate(TotalPoints/TotalMinutesPlayed~Team,NBA1415,max)
#tapply(NBA1415$TotalPoints/TotalMinutesPlayed,NBA1415$Team,max)
NBA1415Maxefficiency<-merge(NBA1415,TotalPoint/TotalMinutesPlayed)
output<-NBA1415Maxefficiency[order(NBA1415Maxefficiency$TotalPoints/TotalMinutesPlayed,decreasing = T),c("Team","Name","Efficiency")]
library(knitr)
kable(output, digits=2)
```
## 各隊三分球出手最準的球員
